### ISSUE TITLE
Link for doc template is invalid

### ISSUE THREAD

**Issue by marvpaul** [Gnork/htw-latex-template#1]
Thanks for sharing the template 👍 
The mentioned doc template is no longer available using this link: http://www.htw-berlin.de/fileadmin/HTW/Zentral/DE/HTW/ZR1_Presse/Mustervorlagen/Muster_Abschlussarbeit_Gruen.doc

**Comment by Gnork** [comment]
I wasn't allowed to redistribute the image, when I created this repo. I think the official .doc is not available anymore. The image used in the .doc was a placeholder anyway and can be replaced with a custom image, which fits the content of the thesis.

Side note: the font size and line height of my template is much smaller than it was in the official doc. Ask your supervisor how many pages (min/max) you should write, when using my template.

**Comment by Gnork** [comment]
This is the front page of my thesis as a reference: 
[thesis-front.pdf](https://github.com/Gnork/htw-latex-template/files/2817202/thesis-front.pdf)

**Comment by marvpaul** [comment]
Thanks for quick response :) 
I could create a pull request with a modified readme which include this information and without the dead link.

**Comment by Gnork** [comment]
This would be nice, I will accept your pull request.

**Comment by marvpaul** [comment]
Pull request sent 👍

**Comment by Gnork** [comment]
Sorry for the late merge and thanks for your contribution. I will close this issue now.
